SELECT D.*,C.*,T.*
FROM "/UI2/FLPSETPD" AS D
INNER JOIN "/UI2/FLPSETC" AS C
ON D.PROPERTY_ID = C.PROPERTY_ID
INNER JOIN "/UI2/FLPSETPDT" AS T
ON D.PROPERTY_ID = T.PROPERTY_ID
WHERE T.LANGU = 'E' AND C.CLIENT LIKE '%'
