SELECT "ORIG" . "ID" , "ORIG" . "PARENTID" , 
COALESCE( "REFM" . "DOMAINID" , "REF" . "DOMAINID" , "ORIG" . "DOMAINID" ) "DOMAINID" , 
"ORIG" . "REFERENCECHIPID" , "ORIG" . "URL" , "REFM" . "URL" "REFM_URL" , 
"REF" . "URL" "REF_URL" , 
COALESCE( "REFM" . "SEM_OBJ" , "REF" . "SEM_OBJ" , "ORIG" . "SEM_OBJ" ) "SEM_OBJ" , 
COALESCE( "REFM" . "SEM_ACT" , "REF" . "SEM_ACT" , "ORIG" . "SEM_ACT" ) "SEM_ACT" , 
COALESCE( "REFM" . "APP_TYPE" , "REF" . "APP_TYPE" , "ORIG" . "APP_TYPE" ) "APP_TYPE" , 
COALESCE( "REFM" . "WD_APPL_ID" , "REF" . "WD_APPL_ID" , "ORIG" . "WD_APPL_ID" ) "WD_APPL_ID" , 
COALESCE( "REFM" . "WD_CONF_ID" , "REF" . "WD_CONF_ID" , "ORIG" . "WD_CONF_ID" ) "WD_CONF_ID" , 
COALESCE( "REFM" . "WD_COMPABILITY_MODE" , "REF" . "WD_COMPABILITY_MODE" , "ORIG" . "WD_COMPABILITY_MODE" ) "WD_COMPABILITY_MODE" , 
COALESCE( "REFM" . "UI5_COMPONENT_ID" , "REF" . "UI5_COMPONENT_ID" , "ORIG" . "UI5_COMPONENT_ID" ) "UI5_COMPONENT_ID" , 
COALESCE( "REFM" . "TCODE" , "REF" . "TCODE" , "ORIG" . "TCODE" ) "TCODE" , 
COALESCE( "REFM" . "WCF_TARGET_ID" , "REF" . "WCF_TARGET_ID" , "ORIG" . "WCF_TARGET_ID" ) "WCF_TARGET_ID" , 
COALESCE( "REFM" . "URLT_ID" , "REF" . "URLT_ID" , "ORIG" . "URLT_ID" ) "URLT_ID" , "ORIG" . "URLT_PARAMETERS" , "REFM" . "URLT_PARAMETERS" "URLT_REFM_PARAMETERS" , "REF" . "URLT_PARAMETERS" "URLT_REF_PARAMETERS" , 
COALESCE( "REFM" . "FORM_FACTOR_DESKTOP" , "REF" . "FORM_FACTOR_DESKTOP" , "ORIG" . "FORM_FACTOR_DESKTOP" ) "FORM_FACTOR_DESKTOP" , 
COALESCE( "REFM" . "FORM_FACTOR_TABLET" , "REF" . "FORM_FACTOR_TABLET" , "ORIG" . "FORM_FACTOR_TABLET" ) "FORM_FACTOR_TABLET" , 
COALESCE( "REFM" . "FORM_FACTOR_PHONE" , "REF" . "FORM_FACTOR_PHONE" , "ORIG" . "FORM_FACTOR_PHONE" ) "FORM_FACTOR_PHONE" , 
"ORIG" . "PARAMETERS" , "REFM" . "PARAMETERS" "REFM_PARAMETERS" , "REF" . "PARAMETERS" "REF_PARAMETERS" , 
COALESCE( "REFM" . "ADD_PARAMS_ALLOWED" , "REF" . "ADD_PARAMS_ALLOWED" , "ORIG" . "ADD_PARAMS_ALLOWED" ) "ADD_PARAMS_ALLOWED" , 
COALESCE( "REFM" . "SYSTEM_ALIAS" , "REF" . "SYSTEM_ALIAS" , "ORIG" . "SYSTEM_ALIAS" ) "SYSTEM_ALIAS" , 
COALESCE( "REFM" . "INFORMATION" , "REF" . "INFORMATION" , "ORIG" . "INFORMATION" ) "INFORMATION" , 
COALESCE( "REFM" . "CONF_TEXT" , "REF" . "CONF_TEXT" , "ORIG" . "CONF_TEXT" ) "CONF_TEXT" , 
"ORIG" . "REFERENCEPARENTID" , "ORIG" . "SHORT_GUID" , 
COALESCE( "REFM_PROPT" . "VALUE" , "REF_PROPT" . "VALUE" , "ORIG_PROPMT" . "VALUE" , "ORIG_PROPT" . "VALUE" ) "VALUE" , 
COALESCE( "REFM_LPD" . "LPD_ROLE" , "REF_LPD" . "LPD_ROLE" , "ORIG_LPD" . "LPD_ROLE" ) "LPD_ROLE" , 
COALESCE( "REFM_LPD" . "LPD_INSTANCE" , "REF_LPD" . "LPD_INSTANCE" , "ORIG_LPD" . "LPD_INSTANCE" ) "LPD_INSTANCE" , 
COALESCE( "REFM_LPD" . "LPD_ALIAS" , "REF_LPD" . "LPD_ALIAS" , "ORIG_LPD" . "LPD_ALIAS" ) "LPD_ALIAS" , 
COALESCE( "REFM_LPD" . "LPD_APP_ID" , "REF_LPD" . "LPD_APP_ID" , "ORIG_LPD" . "LPD_APP_ID" ) "LPD_APP_ID" ,
 4 "SCOPE" , 
 CASE WHEN "REFM" . "ID" IS NOT NULL THEN 4 ELSE ( CASE WHEN "REF" . "ID" IS NOT NULL THEN 5 END ) END "REF_SCOPE" 
 FROM "/UI2/PB_C_TMM" "ORIG" 
 LEFT OUTER JOIN "/UI2/PB_C_TM" "REF" 
 ON "ORIG" . "REFERENCECHIPID" = "REF" . "ID" 
 LEFT OUTER JOIN "/UI2/PB_C_TMM" "REFM" 
 ON "ORIG" . "MANDT" = "REFM" . "MANDT" AND "ORIG" . "REFERENCECHIPID" = "REFM" . "ID" 
 LEFT OUTER JOIN "/UI2/PB_C_PROPT" "ORIG_PROPT" 
 ON "ORIG" . "ID" = "ORIG_PROPT" . "BAG_PARENTID" AND "ORIG_PROPT" . "BAG_ID" = N'tileProperties' 
 AND "ORIG_PROPT" . "NAME" = N'display_title_text' AND "ORIG_PROPT" . "BAG_CATEGORY" = N'C' 
 AND "ORIG_PROPT" . "LANGU" = N'E' 
 LEFT OUTER JOIN "/UI2/PB_C_PROPMT" "ORIG_PROPMT" 
 ON "ORIG" . "MANDT" = "ORIG_PROPMT" . "MANDT" 
 AND "ORIG" . "ID" = "ORIG_PROPMT" . "BAG_PARENTID" AND "ORIG_PROPMT" . "BAG_ID" = N'tileProperties' 
 AND "ORIG_PROPMT" . "NAME" = N'display_title_text' AND "ORIG_PROPMT" . "BAG_CATEGORY" = N'C' 
 AND "ORIG_PROPMT" . "LANGU" = N'E' 
 LEFT OUTER JOIN "/UI2/PB_C_PROPT" "REF_PROPT" 
 ON "REF" . "ID" = "REF_PROPT" . "BAG_PARENTID" AND "REF_PROPT" . "BAG_ID" = N'tileProperties' 
 AND "REF_PROPT" . "NAME" = N'display_title_text' AND "REF_PROPT" . "BAG_CATEGORY" = N'C' AND "REF_PROPT" . "LANGU" = N'E' 
 LEFT OUTER JOIN "/UI2/PB_C_PROPMT" "REFM_PROPT" ON "ORIG" . "MANDT" = "REFM_PROPT" . "MANDT" AND "REFM" . "ID" = "REFM_PROPT" . "BAG_PARENTID" 
 AND "REFM_PROPT" . "BAG_ID" = N'tileProperties' AND "REFM_PROPT" . "NAME" = N'display_title_text' 
 AND "REFM_PROPT" . "BAG_CATEGORY" = N'C' AND "REFM_PROPT" . "LANGU" = N'E' 
 LEFT OUTER JOIN "/UI2/PB_C_TMMLPD" "ORIG_LPD" ON "ORIG" . "MANDT" = "ORIG_LPD" . "MANDT" AND "ORIG" . "ID" = "ORIG_LPD" . "ID" 
 LEFT OUTER JOIN "/UI2/PB_C_TMLPD" "REF_LPD" ON "REF" . "ID" = "REF_LPD" . "ID" 
 LEFT OUTER JOIN "/UI2/PB_C_TMMLPD" "REFM_LPD" ON "ORIG" . "MANDT" = "REFM_LPD" . "MANDT" AND "REFM" . "ID" = "REFM_LPD" . "ID" 
 LEFT OUTER JOIN "/UI2/PB_C_PAGEM" "PAGEM" ON "ORIG" . "MANDT" = "PAGEM" . "MANDT" AND "REF" . "PARENTID" = "PAGEM" . "ID" 
 WHERE "ORIG" . "MANDT" = '600' AND "ORIG" . "PARENTID" LIKE ( N'%ZBC_TS_FI_GL_DISP%' ) 
 AND ( NOT "REFM" . "PARENTID" IS NULL OR NOT "PAGEM" . "ID" IS NOT NULL ) 
 AND ( "REFM" . "ID" IS NULL AND "REF" . "ID" IS NULL 
 AND ( "ORIG" . "SEM_OBJ" <> N'' OR "ORIG" . "SEM_ACT" <> N'' ) 
 AND ( "ORIG" . "SEM_OBJ" <> N'Shell' OR NOT "ORIG" . "SEM_ACT" IN ( N'plugin' , N'bootConfig' ) ) OR "REFM" . "ID" IS NOT NULL AND ( "REFM" . "SEM_OBJ" <> N'' OR "REFM" . "SEM_ACT" <> N'' ) 
 AND ( "REFM" . "SEM_OBJ" <> N'Shell' OR NOT "REFM" . "SEM_ACT" IN ( N'plugin' , N'bootConfig' ) ) OR "REFM" . "ID" IS NULL AND "REF" . "ID" IS NOT NULL 
 AND ( "REF" . "SEM_OBJ" <> N'' OR "REF" . "SEM_ACT" <> N'' ) AND ( "REF" . "SEM_OBJ" <> N'Shell' OR NOT "REF" . "SEM_ACT" IN ( N'plugin' , N'bootConfig' ) ) )
