SELECT 
D.PROPERTY_ID
,D.TYPE
,D.CATEGORY
,D.SEARCH_HELP
,D.DEFAULT_VALUE
,C.ORIGIN
,C.VALUE
,T.DESCRIPTION
,D.PROPERTY_PATH

FROM "/UI2/FLPSETPD" AS D
INNER JOIN "/UI2/FLPSETC" AS C
ON D.PROPERTY_ID = C.PROPERTY_ID
INNER JOIN "/UI2/FLPSETPDT" AS T
ON D.PROPERTY_ID = T.PROPERTY_ID
WHERE T.LANGU = 'E' AND C.CLIENT LIKE '%100%'
